### ISSUE TITLE
Enhancement: Use !secrets

### ISSUE THREAD

**Issue by dekiesel** [freol35241/ltss#1]
Thank you for the addon, it works very well in my setup.

Would it be possible to use !secrets so that the password doesn't have to be saved in the config?

**Comment by freol35241** [comment]
Hi,

As the configuration of this custom component is part of you usual HomeAssistant configuration there is nothing stopping you from using !secrets.

https://www.home-assistant.io/docs/configuration/secrets/

For the db_url parameter, you would put the whole url as a secret, including the username and password for the connection. See link below for example.

https://community.home-assistant.io/t/recorder-to-mysql-using-secrets-file/16649

Hope this helps!
