### ISSUE TITLE
Create index on (entity_id, time)

### ISSUE THREAD

**Issue by sithmein** [freol35241/ltss#10]
Currently the TimescaleDB extension creates two indexes, on on entity_id and one on time. However, most queries will filter by both entity and time and therefore a compound index on both (entity_id, time DESC) will improve those queries considerably. The TimescaleDB manual also suggests creating such indexes.

**Comment by freol35241** [comment]
@sithmein 
thanks for making me aware of this! I assume you are referring to the following in the TimescaleDB docs: https://docs.timescale.com/latest/using-timescaledb/schema-management#indexing-best-practices

This is a no-brainer, see my proposed fix in #11 
As part of this I believe the existing index on only entity_id is no longer needed. Do you agree?

**Comment by sithmein** [comment]
Yes, the single-column index on _entity\_id_ is not necessary any more. Thanks for addressing it so quickly!
