### ISSUE TITLE
Feature Request: include/exclude `entity_globs` as in the `recorder` component of homeassistant

### ISSUE THREAD

**Issue by boesing** [freol35241/ltss#18]
Hey there,

I recently had the need of using `entity_globs` as I've added an entity to have the amount of seconds a switch is in its position. 

To keep homeassistant and ltss in sync, I wanted to apply the same settings to this component aswell.
Sadly, it does not support it (yet).

I am willing to contribute but I dont have time for that for the moment.
If you are planning to work on it, please let me know.
If others want to contribute, please do so.

I'll just create this feature request to keep track on this.

Thanks!

**Comment by freol35241** [comment]
Thanks for creating the issue! Will make sure to update you if I get around to it at some point.

**Comment by freol35241** [comment]
@boesing 

A PR for this now exists in #22 . Would you mind trying this one out and verify that it matches what you had in mind?

**Comment by boesing** [comment]
Dang! Lucky me, I've yesterday started implementing `numeric` template sensors to display boolean values in https://github.com/kalkih/mini-graph-card#alternate-y-axis
Thus I have to add multiple new sensors which I do not want to track (as the original values are more interesting).
I was in this issue yesterday and thought "jeez, could need that, maybe I'm going to contribute it by myself".

So yeah, will definitely going to check if the PR is working 👍🏼 
Thats really appreciated!

**Comment by boesing** [comment]
Just a quick update: I did not manage to test it, but I definitely will when I find some time to play with it any time soon.
