### ISSUE TITLE
No version key in manifest file (deprecation warning in HA logs)

### ISSUE THREAD

**Issue by tvandyck** [freol35241/ltss#26]
`2021-04-20 09:59:25 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'ltss'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'ltss'
`

**Comment by freol35241** [comment]
@tvandyck thanks for reporting!
