### ISSUE TITLE
[FR] Please add support for HACS

### ISSUE THREAD

**Issue by CM000n** [freol35241/ltss#3]
And as a Feature Request: Could you maybe also please add HACS support to ltss?
I just think it would help ltss to be known to a wider audience and make it easier to track features and fixes.
Seems you’ll have to restructure your repo a bit for that:
https://github.com/hacs/default

Thanks in advance

**Comment by CM000n** [comment]
Hall @freol35241 , I created a small merge request that changes the structure of your repo a little bit and adds additional info to make it HACS compatible: https://github.com/freol35241/ltss/pull/4

After that you have to add a description and some topics to your repo yourself, so it will be displayed correctly in HACS and can be found easier.

When this is done, you can add it to the list of official HACS repos here (just create a little PR that adds it to the integration list): https://github.com/hacs/default

Greetings an many thanks in advance

**Comment by freol35241** [comment]
hacs/default#386

**Comment by freol35241** [comment]
hacs/default#386 is now merged
