### ISSUE TITLE
Add option to skip attributes?

### ISSUE THREAD

**Issue by silvanverschuur** [freol35241/ltss#34]
To reduce the size of the database I would like to skip the attributes of each entity because I'm only interested in the state. Is this possible, or could this be a configuration option?

**Comment by Yamakaky** [comment]
Did you try enabling the compression? On my db I get 97% disk savings, that should help with your problem. https://docs.timescale.com/timescaledb/latest/how-to-guides/compression/about-compression/

**Comment by silvanverschuur** [comment]
No, I have not tried enabling compression. Thanks for the tip!

**Comment by Yamakaky** [comment]
See https://github.com/freol35241/ltss/issues/25 for the compression parameters I use.
