### ISSUE TITLE
Try out compatibility with `timescale-docker-ha`

### ISSUE THREAD

**Issue by freol35241** [freol35241/ltss#36]
It seems timescale has once again started to support/include postgis into their official docker images, notably https://github.com/timescale/timescaledb-docker-ha/.

Needs to be verified.

**Comment by rikroe** [comment]
Just moved from `timescale/timescaledb-postgis:latest-pg12` to `timescale/timescaledb-ha:pg14-latest`.

Updated PostgreSQL through the usual [shenanigans](https://docs.timescale.com/timescaledb/latest/how-to-guides/backup-and-restore/pg-dump-and-restore/) (`pg_dump` on `pg12`, `pg_restore` with timescale stuff on `pg14`).

One thing to note is that the `data` folder inside the container has changed:
```yaml
- /opt/homeserver/postgresql/data/12:/var/lib/postgresql/data # image: timescale/timescaledb-postgis:latest-pg12
- /opt/homeserver/postgresql/data/14:/home/postgres/pgdata/data  # timescale/timescaledb-ha:pg14-latest
```

So far no issues and data is flowing into the hypertable.

**Comment by freol35241** [comment]
@rikroe Thanks for taking the time to report this! Much appreciated 👍
