### ISSUE TITLE
ltss not working since home assistant 2023.3.0b0 release

### ISSUE THREAD

**Issue by pimw1** [freol35241/ltss#43]
Hi,

ltss is not working anymore since 2023.3.0b0 release. It's working fine for 2023.2.x. See below the error.
With this release, SQL alchemy is bumped to version 2.

> Logger: homeassistant.util.package
> Source: util/package.py:107
> First occurred: 23:14:17 (3 occurrences)
> Last logged: 23:14:31
> 
> Unable to install package sqlalchemy>=1.0,<2.0: ERROR: Cannot install sqlalchemy<2.0 and >=1.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip
> 
> 
> Logger: homeassistant.setup
> Source: setup.py:205
> First occurred: 23:14:52 (1 occurrences)
> Last logged: 23:14:52
> 
> Setup failed for custom integration ltss: Requirements for ltss not found: ['sqlalchemy>=1.0,<2.0']

**Comment by velaar** [comment]
Can reproduce in 2023.3.0b1 as well

**Comment by freol35241** [comment]
Thanks for reporting this. Most probably this is due to the fact that SQLAlchemy has (since approx a month) released version 2.0. 

You could try to just loosen the LTSS requirement (i.e. remove the `< 2.0`) in the requirements. But please be aware that I have not yet had the time to test if the LTSS code is compatible!

**Comment by freol35241** [comment]
Yes, SQLAlchemy has been bumped from 1.4 to 2.0 (https://github.com/home-assistant/core/pull/86436).

Further, the ltss code base is not directly compatible with SQLAlchemy >= 2.0 but requires some updates.

**Comment by freol35241** [comment]
https://github.com/home-assistant/developers.home-assistant/issues/606

**Comment by freol35241** [comment]
A pre-release with support for Home Assistant 2023.3 has now been released (https://github.com/freol35241/ltss/releases/tag/v2.0.0-alpha). Please try it out and report back,

A proper release will be made as soon as Home Assistant 2023.3 is no longer in beta stage.

**Comment by pimw1** [comment]
Thank you for the pre-release! I've tested it, but it's not working. It generates the following errors:

> This error originated from a custom integration.
> 
> Logger: custom_components.ltss
> Source: custom_components/ltss/__init__.py:225
> Integration: Long Time State Storage (LTSS) (documentation)
> First occurred: 11:20:51 (1 occurrences)
> Last logged: 11:20:51
> 
> Error executing query: 'Session' object has no attribute 'transaction'

> This error originated from a custom integration.
> 
> Logger: root
> Source: custom_components/ltss/__init__.py:97
> Integration: Long Time State Storage (LTSS) (documentation)
> First occurred: 11:20:51 (1 occurrences)
> Last logged: 11:20:51
> 
> Uncaught thread exception
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "/config/custom_components/ltss/__init__.py", line 225, in run
>     with session_scope(session=self.get_session()) as session:
>   File "/usr/local/lib/python3.10/contextlib.py", line 142, in __exit__
>     next(self.gen)
>   File "/config/custom_components/ltss/__init__.py", line 97, in session_scope
>     if session.transaction:
> AttributeError: 'Session' object has no attribute 'transaction'
> 
>

**Comment by pimw1** [comment]
Just to be sure, i've removed the __pycache__ folder too, followed by a home assistant reboot. This did not solve the issue. I'm running Home Assistant OS.

**Comment by pimw1** [comment]
I'll write down the exact steps i took:
1: full backup created of home assistant version 2023.2.5
2: replacing the __init__.py, manifest.json, migrations.py and models.py. Keeping the __pycache__ intact.
3: install home assistant 2023.3.0b3, followed by an automatic reboot. 
4: the mentioned error appears
5: removed the __pycache__ folder
6: reboot home assistant
7: the mentioned error appears again
8: rollback of the home assistant backup

**Comment by freol35241** [comment]
Hmm, thanks for reporting back @pimw1 . Apparently, I was overly confident in the test coverage / CI pipeline...

This will take some more time to get fixed since I dont have a good testing setup for it locally. Preferably, the test coverage / CI pipeline setup should be updated to increase confidence when bugfixes need to be performed (#24)

**Comment by freol35241** [comment]
@pimw1 I have now made another pre-release (https://github.com/freol35241/ltss/releases/tag/v2.0.0-beta) which should have fixed the error you encountered. If possible, please try it out and report back!

**Comment by pimw1** [comment]
It's working fine now. Awesome!! Thank you very much.
