### ISSUE TITLE
Component has to be configured in configuration.yaml not packages

### ISSUE THREAD

**Issue by eifinger** [freol35241/ltss#5]
For whatever reasons it is not possible to configure this component as a package. I could only get it to work when I put the configuration directly in the configuration.yaml file.

If you want, you can put the information into the README

**Comment by freol35241** [comment]
@eifinger thanks for raising this issue. Can I ask you to be a little more specific?
* I assume you are talking about this configuration option? https://www.home-assistant.io/docs/configuration/packages/ 
* What do you mean by "not possible"? Do you get any error messages?

**Comment by eifinger** [comment]
Yes the option `include_dir_named`.
I get the error `equired key not provided @ data['ltss']['db_url']`

Here is the failing config check in my repo:
https://github.com/eifinger/homeassistant-config/runs/672115430

**Comment by freol35241** [comment]
Ok, I am not using the package syntax myself and really have no idea why this shouldnt work. Your config looks sound to me.

A suggestion is to try to move the regular recorder component into a package and see if that works: https://github.com/eifinger/homeassistant-config/blob/master/configuration.yaml#L67-L72

LTSS has an almost identical config so if the recorder component work as part of a package and LTSS does not, then something is not quite right...

**Comment by Expaso** [comment]
I think the regular recorder component is also broken. But there the db_url is optional, so no error will be raised there.

**Comment by freol35241** [comment]
@Expaso thanks for digging in to this. I tested your suggested schema change in my setup (wo yaml package syntax) and it seems to work fine.

@eifinger do you care to give this (#7) a try to confirm that it solves your problem?

**Comment by eifinger** [comment]
I can confirm that the PR solves the issue.
