### ISSUE TITLE
sqlalchemy problem: "Requirements for ltss not found"

### ISSUE THREAD

**Issue by gschmidl** [freol35241/ltss#52]
Updating to Home Assistrant 2023.3.0 and ltss 2.0.1, I get this when trying to restart:

`The system cannot restart because the configuration is not valid: Integration error: ltss - Requirements for ltss not found: ['sqlalchemy>=1.0,<2.0'].`

Caused by, presumably,

`Setup failed for custom integration ltss: Requirements for ltss not found: ['sqlalchemy>=1.0,<2.0'].`

Which in turn comes from

`2023-03-02 07:37:10.778 ERROR (SyncWorker_9) [homeassistant.util.package] Unable to install package sqlalchemy>=1.0,<2.0: ERROR: Cannot install sqlalchemy<2.0 and >=1.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`

**Comment by freol35241** [comment]
Hi,

The manifest.json for v2.0.1 can be found here: https://github.com/freol35241/ltss/blob/v2.0.1/custom_components/ltss/manifest.json

It clearly states `"sqlalchemy>=2.0,<3.0"`

Can you please confirm that you have actually upgraded LTSS to v2.0.1 ?

**Comment by gschmidl** [comment]
I redownloaded 2.0.1 specifically inside HACS just now and the issue seems to persist. Where else can I check it's the correct version?

![image](https://user-images.githubusercontent.com/20334/222502600-06c3663d-f215-4bcc-888f-b24a55bb95b9.png)

**Comment by freol35241** [comment]
The best way to check is to look at what is actually inside your custom_components directory. 

Also, don't forget to restart home assistant after downloading custom components with hacs.

**Comment by gschmidl** [comment]
That's the thing - it won't let me restart because of the dependency error.

![image](https://user-images.githubusercontent.com/20334/222508944-92d31f7e-2249-4305-81f4-9952c6c9ebad.png)

![image](https://user-images.githubusercontent.com/20334/222509147-be7aec60-5e9a-40de-9ffe-5f9c3520910e.png)

**Comment by freol35241** [comment]
Hmm, that's weird catch 22 but not much I can do from the ltss side. I think you are better of raising this as an issue in hacs and/or home assistant.

I guess a workaround is to simply do a reboot to force a restart of home assistant.

**Comment by verstrepeng** [comment]
I have the same issue after the update
```
Logger: homeassistant.util.package
Source: util/package.py:100
First occurred: 13:46:11 (3 occurrences)
Last logged: 13:46:15

Unable to install package sqlalchemy>=2.0,<3.0: ERROR: Cannot install sqlalchemy<3.0 and >=2.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 23.0.1 [notice] To update, run: pip install --upgrade pip
```
I did a rollback to v1.1.0

**Comment by verstrepeng** [comment]
Rollback didn't work... problem persists.

**Comment by freol35241** [comment]
@verstrepeng 
Have you:
1. Upgrade home assistant to at least 2023.3.0
2. Upgrade ltss to at least v2.0.1
3. Restarted home assistant (or rebooted the machine if home assistant won't let you restart)
