### ISSUE TITLE
Convert attributes column to jsonb

### ISSUE THREAD

**Issue by Expaso** [freol35241/ltss#6]
I think it can be beneficial for both speed and space to implement the 'attributes' column as JSONB datatype instead of text.
This way, you can also index it by:

`create index idxAttributes on ltss USING gin (attributes)`

And from here create effecient indexed queries like:

```
select * from ltss where attributes @> '{
    "icon": "mdi:delete-empty"
}'
```

**Comment by jaakla** [comment]
As workaround you can create same index with 
`create index idxAttributes on ltss USING gin ((attributes::JSONB)) `

But original field type change would be more effective for sure.

**Comment by Expaso** [comment]
In my installation I have already converted the column to JSONB, and created the index.
This works fine, since every records looks like valid JSON.

I just thought it would just be a nice 'performance-by-default'.

**Comment by freol35241** [comment]
thanks for the interesting suggestions. The initial reason for using `text` as type was to be generic enough to support any changes made in how Home Assistant represent attributes internally, but maybe that is unlikely to change.

@Expaso Do you have any indication of the time it takes to convert from `text` to `jsonb`? In relation to db size.

@jaakla  do you have any idea about the performance penalty of this workaround in comparison with changing the type?

**Comment by Expaso** [comment]
Well, it really all depends on the hardware. I converted this column with 1gb of data in just under a minute on a rpi4, 4gb ram using usb3 enclosure.

**Comment by elupus** [comment]
It would at least be nice if it was formatted as json type. That way you can query it easier without having to cast it to json before doing the query.

**Comment by freol35241** [comment]
Sorry for not being too responsive for a while. Yes, this is a good idea and I have now finally found some time to spend on it.

Can someone in addition to myself give #9 a try? Please read the NOTE in the README.

**Comment by Expaso** [comment]
Heej Thanks @freol35241 !
Mine was already converted ofcourse, but it's nice to see this one closed!
